sudo: required
language: generic
services:
  - docker 
before_install:
  - docker build -t srikanthdevarampati/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true srikanthdevarampati/docker-react npm run test


   
